name: sandokti
description: Sandokti - Budget marocain premium
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1

  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.6

  http: ^1.2.2

  # ✅ AJOUT IMAGE + STORAGE
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2

  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

  # Vertex AI in Firebase
  firebase_ai: ^3.11.0

  # PDF export
  pdf: ^3.11.0
  printing: ^5.13.4
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/sandokti_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0B2A2A"
  adaptive_icon_foreground: "assets/logo/sandokti_logo.png"
  web:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/patterns/zellige.png
    - assets/logo/sandokti_logo.png