// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ewVGiK9FE7auKP9f3RIYpoMcn5-jHEI',
    appId: '1:725919981685:web:1c9387b4c61bbc2994583c',
    messagingSenderId: '725919981685',
    projectId: 'sandokti',
    authDomain: 'sandokti.firebaseapp.com',
    storageBucket: 'sandokti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4a2pqVngcssvMXMDKGhoF41GToFbgS5A',
    appId: '1:725919981685:android:d94c964206d40ed294583c',
    messagingSenderId: '725919981685',
    projectId: 'sandokti',
    storageBucket: 'sandokti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoXuXlfGJMPfK_bmYmaVL3eTYiMMm9IlM',
    appId: '1:725919981685:ios:4b87d8521e71d79a94583c',
    messagingSenderId: '725919981685',
    projectId: 'sandokti',
    storageBucket: 'sandokti.firebasestorage.app',
    iosBundleId: 'com.example.sandokti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoXuXlfGJMPfK_bmYmaVL3eTYiMMm9IlM',
    appId: '1:725919981685:ios:4b87d8521e71d79a94583c',
    messagingSenderId: '725919981685',
    projectId: 'sandokti',
    storageBucket: 'sandokti.firebasestorage.app',
    iosBundleId: 'com.example.sandokti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ewVGiK9FE7auKP9f3RIYpoMcn5-jHEI',
    appId: '1:725919981685:web:2b2343831bc7dd1694583c',
    messagingSenderId: '725919981685',
    projectId: 'sandokti',
    authDomain: 'sandokti.firebaseapp.com',
    storageBucket: 'sandokti.firebasestorage.app',
  );
}
